// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA93C4_iGAHlmL9pP_Gjo_UeI1PSy4ch9c',
    appId: '1:960872978535:web:6eb6ed7a3d8e8593df1cc2',
    messagingSenderId: '960872978535',
    projectId: 'task-manager-d5344',
    authDomain: 'task-manager-d5344.firebaseapp.com',
    storageBucket: 'task-manager-d5344.appspot.com',
    measurementId: 'G-7HD96XSLE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9WakykaqgNFM-OvfT3vtMmz-IquT28TI',
    appId: '1:960872978535:android:eb7e72201032cf16df1cc2',
    messagingSenderId: '960872978535',
    projectId: 'task-manager-d5344',
    storageBucket: 'task-manager-d5344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtcE5nIXsjpO5zpjs0xhibMZWprVvBTZQ',
    appId: '1:960872978535:ios:da8d88429111d9b9df1cc2',
    messagingSenderId: '960872978535',
    projectId: 'task-manager-d5344',
    storageBucket: 'task-manager-d5344.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtcE5nIXsjpO5zpjs0xhibMZWprVvBTZQ',
    appId: '1:960872978535:ios:ae84e5c2b9b71ac3df1cc2',
    messagingSenderId: '960872978535',
    projectId: 'task-manager-d5344',
    storageBucket: 'task-manager-d5344.appspot.com',
    iosBundleId: 'com.example.taskManager.RunnerTests',
  );
}
